cargo-features = ["per-package-target"]

[workspace]
members = [
    "crates/example-wasmtime-host",
    "crates/example-wasm",
    "crates/wasi-interface-gen",
]
default-members = ["crates/example-wasmtime-host"]

