[package]
name = "example-wasmtime-host"
version = "0.1.0"
edition = "2018"

[dependencies]
wasmtime = "0.31.0"
wasmtime-wasi = "0.31.0"
anyhow = "1.0"
wai-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wai-bindgen.git"}

