[package]
name = "example-wasmtime-host"
version = "0.1.0"
edition = "2018"

[dependencies]
wasmtime = "0.34.1"
wasmtime-wasi = "0.34.1"
anyhow = "1.0"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen.git"}

