on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI/CD
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-wasi
          default: true

      - uses: actions-rs/cargo@v1
        with:
          command: run

      - uses: Swatinem/rust-cache@v1
